#!/usr/bin/perl
use strict;
use warnings;
use Getopt::Long;
use Pod::Usage;

GetOptions (
    'h|help|?' => sub { pod2usage(2) },
    'version' => \my $version,
    'count=i' => \my $count,
    'number' => \my $number,
    );

if ($version) {
    print "Version my_cat: 0.03\n";
    exit;
}

if ( $count ) {
    if ( @ARGV > 0 ) {
        my $arg_0 = shift;
        print_count_line_file_up($count,$arg_0);
    }
    exit;
}

if ( $number ) {
    if ( @ARGV > 0 ) {
        my $arg_2 = shift;
        out_number_line($arg_2);
    }
    exit;
}

if ( @ARGV > 0 ) {
    my $arg_1 = shift;
    full_print_file($arg_1);
}
else {
    print "Argument not found!\n";
    exit;
}

sub print_count_line_file_up {
    my $number = shift;
    my $file = shift;
    open(my $fh, '<', $file) or die $!;
    for (my $i = 0; $i<$number; $i++) {
        while ( my $line = <$fh> ) {
            chomp($line);
            print($line . "\n");
            last;
        }
    }
    close($fh);
}


sub full_print_file {
    my $file = shift;
    open(my $fh, '<', $file) or die $!;
    while ( my $line = <$fh> ) {
        chomp($line);
        print($line . "\n");
    }
    close($fh);
}

sub out_number_line {
    my $file = shift;
    my $n = 0;
    open(my $fh, '<', $file) or die $!;
    while ( my $line = <$fh> ) {
        chomp($line);
        $n += 1;
        print($n, "  ", $line . "\n");
    }
    close($fh);
}

__END__

=head1 NAME

my_cat - утилита для вывода содержимого одного или нескольких текстовых файлов на экран.

=head1 SYNOPSIS

my_cat [options] [file]

    Options:
        --help,    -h  Вывод справочной информации по my_cat
        --version  -v  Версия программы
        --count    -c  Выводит n-количество строк с начала файла
        --number   -n  Нумерация всех строк по мере их записи на стандартный вывод